name: Pytest and code Coverage

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  schedule:
    # Run every night at 04:00 (GitHub Actions timezone)
    # in order to catch when unfrozen dependency updates
    # break the use of the library.
    - cron: '4 0 * * *'

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Install required system packages for Ubuntu
        run: sudo apt-get install -y python3-pip libsecp256k1-dev python3-coverage
        if: startsWith(matrix.os, 'ubuntu-')

      - name: Install required system packages for macOS
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew update
          brew tap cuber/homebrew-libsecp256k1
          brew install libsecp256k1
          brew install automake

      - run: python3 -m venv /tmp/venv
      - run: /tmp/venv/bin/python -m pip install --upgrade pip hatch coverage

        # Only run coverage on one OS
      - run: /tmp/venv/bin/hatch run testing:test

      - name: Run tests with coverage
        run: |
          /tmp/venv/bin/hatch run testing:cov
          echo "After tests:"
          ls -la
          ls -la ./coverage.xml
        shell: bash

      - name: List directory contents after tests
        run: |
          echo "After tests:"
          pwd 
          ls -la
        shell: bash

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true